<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>e738a0ad-1373-44c0-b677-3c18c5e6bc9f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Docker" Version="13.4.6" />
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
      <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\BzsOIDC.Idp\BzsOIDC.Idp.csproj" />
      <ProjectReference Include="..\BzsOIDC.Idp.Migrator\BzsOIDC.Idp.Migrator.csproj" />
    </ItemGroup>

</Project>
